[package]
name = "tsp-solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui_graphs = "0.20.0"
eframe = "0.27.2"
petgraph = "0.6.4"