[package]
name = "tsp-solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.27.2"
petgraph = "0.6.4"
plotters = "0.3.5"
rand = "0.8.5"